# FIXME: someday we may need to handle installing into non-lib.
debian/tmp-udeb/lib/ld*.so* lib
debian/tmp-udeb/lib/libm-*.so* lib
debian/tmp-udeb/lib/libm.so* lib
debian/tmp-udeb/lib/libdl*.so* lib
debian/tmp-udeb/lib/libresolv*.so* lib
debian/tmp-udeb/lib/libc-*.so* lib
debian/tmp-udeb/lib/libc.so* lib
debian/tmp-udeb/lib/libutil* lib
debian/tmp-udeb/lib/libcrypt* lib
# FIXME: This should be with_threads arch's only.
debian/tmp-udeb/lib/libpthread*.so* lib

