# This file is used for making 64-bit libraries development packages.
TMPDIR/usr/lib*/libanl.a usr/libDESTLIBDIR
TMPDIR/usr/lib*/libBrokenLocale.a usr/libDESTLIBDIR
TMPDIR/usr/lib*/libbsd-compat.a usr/libDESTLIBDIR
TMPDIR/usr/lib*/libc.a usr/libDESTLIBDIR
TMPDIR/usr/lib*/libc_nonshared.a usr/libDESTLIBDIR
TMPDIR/usr/lib*/libcrypt.a usr/libDESTLIBDIR
TMPDIR/usr/lib*/libdl.a usr/libDESTLIBDIR
TMPDIR/usr/lib*/libg.a usr/libDESTLIBDIR
TMPDIR/usr/lib*/libieee.a usr/libDESTLIBDIR
TMPDIR/usr/lib*/libm.a usr/libDESTLIBDIR
TMPDIR/usr/lib*/libmcheck.a usr/libDESTLIBDIR
TMPDIR/usr/lib*/libnsl.a usr/libDESTLIBDIR
TMPDIR/usr/lib*/libpthread.a usr/libDESTLIBDIR
TMPDIR/usr/lib*/libpthread_nonshared.a usr/libDESTLIBDIR
TMPDIR/usr/lib*/libresolv.a usr/libDESTLIBDIR
TMPDIR/usr/lib*/librpcsvc.a usr/libDESTLIBDIR
TMPDIR/usr/lib*/librt.a usr/libDESTLIBDIR
TMPDIR/usr/lib*/libutil.a usr/libDESTLIBDIR

TMPDIR/usr/lib*/*.o usr/libDESTLIBDIR
TMPDIR/usr/lib*/*.so usr/libDESTLIBDIR
