#! /bin/sh
set -e

# We remove a relic of the past /usr/doc/<package> symlinks.
# This script should keep at least until sarge release.
package=`basename $0 .postinst`
if [ -L "/usr/doc/$package" ]; then
    rm -f "/usr/doc/$package"
fi

if [ "$1" = configure ]; then
    update-rc.d nscd defaults 19 > /dev/null
    /etc/init.d/nscd restart
fi
exit 0
