#!/bin/sh
set -e

if [ "$1" = configure ]; then
    install-info --quiet --section '^GNU Libraries:' 'GNU Libraries:' \
    /usr/share/info/libc.info.gz

    if command -v install-docs >/dev/null 2>&1; then
	echo -n "Registering GNU C Library Documentation..."
	install-docs -i /usr/share/doc-base/glibc-manual >/dev/null 2>&1
	echo "done."
    fi
    if [ -d /usr/doc ]; then
	package=$(basename $0 .postinst)
	if [ ! -e /usr/doc/$package ]; then
	    (cd /usr/doc;
		if [ -d ../share/doc/$package ]; then
		    ln -s ../share/doc/$package $package ;
		fi
            )
	fi
    fi
fi

