#!/bin/sh
set -e

if [ "$1" = configure ]; then
    install-info --quiet --section '^GNU Libraries:' 'GNU Libraries:' \
    /usr/share/info/libc.info.gz

    if command -v install-docs >/dev/null 2>&1; then
	echo -n "Registering GNU C Library Documentation..."
	install-docs -i /usr/share/doc-base/glibc-manual >/dev/null 2>&1
	echo "done."
    fi
fi

# We remove a relic of the past /usr/doc/<package> symlinks.
# This script should keep at least until sarge release.
package=`basename $0 .postinst`
if [ -L "/usr/doc/$package" ]; then
    rm -f "/usr/doc/$package"
fi
