.\" Placed in the Public Domain by Sebastian Rittau <srittau@jroger.in-berlin.de>.
.Dd January 08, 2001
.Dt NSCD_NISCHECK 8
.Os "GNU C Library 2.2"
.Sh NAME
.Nm nscd_nischeck
.Nd check NIS+ tables for read permissions
.Sh SYNOPSIS
.Nm nscd_nischeck
.Ar OPTION | TABLE
.Sh DESCRIPTION
.Nm Nscd_nischeck
checks if everybody has read permissions for a given NIS+ table and returns 0
if this is the case or 1
if only authenticated users can read the table.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl ? , Fl -help
Print a short help list.
.El
.Bl -tag -width Ds
.It Fl -usage
Print a short usage message.
.El
.Bl -tag -width Ds
.It Fl V , Fl -version
Print program version.
.El
.Sh SEE ALSO
GNU C Library info file,
.Xr nscd 8
